# Generated by Django 5.0 on 2024-03-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='univ_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='images/default/Default_pfp.jpg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Postimages',
        ),
    ]
