# Generated by Django 5.0 on 2024-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
